included:
  - secantTests/
  - secantUITests/

excluded:
  - secant/
  - xctemplates/

disabled_rules:
  - notification_center_detachment
  - orphaned_doc_comment
  - todo
  - unused_capture_list
  - nesting
  - multiple_closures_with_trailing_closure
  - generic_type_name
  - redundant_void_return
  - implicitly_unwrapped_optional
  - force_unwrapping
  - type_body_length
  - function_body_length
  - file_length
  - cyclomatic_complexity
  - force_cast
  - force_try
  - function_parameter_count
  - identifier_name
  - large_tuple
  - empty_parentheses_with_trailing_closure
  - line_length

opt_in_rules:
  - mark
  - array_init
  - async_without_await
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - colon
  - comma_inheritance
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - contrasted_opening_brace
  - convenience_type
  - empty_collection_literal
  - empty_count
  - empty_string
  - fatal_error_message
  - first_where
  - identical_operands
  - indentation_width
  - last_where
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - pattern_matching_keywords
  - return_arrow_whitespace
  - strict_fileprivate
  - superfluous_else
  - unhandled_throwing_task
  - unneeded_escaping
  - unneeded_parentheses_in_closure_argument
  - variable_shadowing
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - todos

analyzer_rules:
  - unused_import

custom_rules:
  array_constructor:
    name: "Array/Dictionary initializer"
    regex: '[let,var] .+ = (\[.+\]\(\))'
    capture_group: 1
    message: "Use explicit type annotation when initializing empty arrays and dictionaries"
    severity: warning

  nslog_function_usage:
    included: ".*\\.swift"
    name: "Swift NSLog() should not be used in App Code"
    regex: "NSLog\\("
    message: "The swift NSLog function should not be used."
    severity: error

  todos:
    included: ".*\\.swift"
    name: "TODO"
    regex: '(TODO|FIXME):\ ([^\[]|\[[^#]|\[#[^1-9])'
    message: "TODO or FIXME without issue number. Format TODO: [#...]"
    severity: warning
    match_kinds:
      - comment

  explicit_type_init:
    included: ".*\\.swift"
    name: "Explicit Type Init"
    regex: '(?<!super)(?<!self)\.init\('
    message: "Use TypeName() instead of .init() or Self.init()"
    severity: error

attributes:
  always_on_same_line:
    - "@IBSegueAction"
    - "@IBAction"
    - "@NSManaged"
    - "@objc"

legacy_hashing: error

indentation_width:
  indentation_width: 4

line_length:
  warning: 150
  error: 150
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

multiline_arguments:
  first_argument_location: next_line
  only_enforce_after_first_closure_on_first_line: true

private_over_fileprivate:
  validate_extensions: true

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

vertical_whitespace:
  max_empty_lines: 1
